
= kitchensink: Assortment of technologies including Arquillian

[abstract]
The `kitchensink` quickstart demonstrates a {javaVersion} web-enabled database application using JSF, CDI, EJB, JPA, and Bean Validation.

:standalone-server-type: default
:archiveType: war
:uses-h2:
:uses-ds-xml:

//*************************************************
// Shared CD and Product Release content
//*************************************************

== What is it?

The `kitchensink` quickstart is a deployable Maven 3 project designed to help you get your foot in the door developing with {javaVersion} on {productNameFull}.

It demonstrates how to create a compliant {javaVersion} application using JSF, CDI, JAX-RS, EJB, JPA, and Bean Validation. It also includes a persistence unit and some sample persistence and transaction code to introduce you to database access in enterprise Java.

== Access the Application

The application will be running at the following URL: http://localhost:8080/{artifactId}/.

== Server Log: Expected Warnings and Errors

You will see the following warnings in the server log. You can ignore these warnings.

[source,options="nowrap"]
----
WFLYJCA0091: -ds.xml file deployments are deprecated. Support may be removed in a future version.

HHH000431: Unable to determine H2 database version, certain features may not work
----

== Open the project via CodeReady Workspaces on Developer Sandbox

https://workspaces.openshift.com/f?url=https://github.com/danieloh30/eap-gitssh-app
